### ISSUE TITLE
Feature request: accessing page data in track events

### ISSUE THREAD

**Issue by javidjamae** [DavidWells/analytics#111]
Love the library! One thing we've been wanting to do is wire in pageData that is available in `page()` events in our `track()` events as well.

Is there any way to configure a `track()` call to get the pageData? Or, is there a way to access `getPageData()` and just manually wire in the page data ourselves?

Glad to take a stab at a PR if this is something you're interested in adding to the project.

Thanks!

P.S. Have you considered enabling the "Discussions" feature in GitHub for this project?

**Comment by DavidWells** [comment]
Hey, thanks for the kind words.

> Is there any way to configure a track() call to get the pageData?

You can use the `page` state for the values and previous values

```js
const pageState = analytics.getState('page')
console.log('page state', pageState)
// do stuff with page state

// fire track with page data
analytics.track('foobar', { foo: 'bar', ...pageData.last })
```

Out of curiosity, what kind of data do you need in the tracking call?

> P.S. Have you considered enabling the "Discussions" feature in GitHub for this project?

No, but that's a good idea 😃. Is that available for all repos now?

**Comment by javidjamae** [comment]
> You can use the page state for the values and previous values

Awesome! That's seriously useful, but wasn't obvious from the docs. 🙏 

> Out of curiosity, what kind of data do you need in the tracking call?

So, I've done a few projects now where the analytics and BI teams want all the page data on every client event so that they can use it for easier segmentation and filtering. Also, knowing things like browser dimensions can help to understand click conversions on different responsive UIs. e.g. you shrink down to mobile and a secondary CTA disappears. You might want to filter the conversion based on browser dimensions to know that how the primary CTA conversions on mobile vs. desktop stack up. Stuff like that.. I've just found that it's just good to have more data on the track events, even if you don't always use it.

> No, but that's a good idea 😃. Is that available for all repos now?

Not sure, I've seen it on a ton of open source repos now, but didn't think that it might be on a progressive rollout.

**Comment by javidjamae** [comment]
If anybody else looking to do this, you'll just need to know how to access the `instance` (which is available in the params passed in to `track`) so that you can call `getState` on it:

```
track: ( { payload, instance } ) => {
  const pageDataProperties = instance.getState( 'page' )?.last?.properties
  payload.properties = {
    ...pageDataProperties,
    ...payload.properties,
  }
  // ...
}
```

**Comment by nuc** [comment]
Hey there,

We stumbled upon the same issue, and unfortunately, the suggested solutions don't always work.

We require events to contain the originating page's information, and there are cases where an event is triggered right after a pageview is sent.

That can lead to race conditions, where the track event is called before the pageview has been finished, so the state doesn't contain the page information yet.

We thought about two different approaches to solving the problem. One would be to expose the `getPageData` helper so that it can be used inside our `track` method.

The other approach would be to always enrich track's data properties with page information, as prepared on this [draft PR](https://github.com/karelchudej/analytics/pull/1/files).

Do you think it's an acceptable solution, or is there a chance where it may lead to unexpected results?

Thanks a lot and looking forward to your response.
