### ISSUE TITLE
Can I use this package instead of Segment?

### ISSUE THREAD

**Issue by zeckdude** [DavidWells/analytics#164]
It seems to me like this package sends data (events, identify, etc) to the various plugins that I specify. Isn't that basically what Segment is doing when it accepts one method call and then sends that data to various other destinations? Can I just use this package instead of Segment? Why would I want to use both?

**Comment by zeckdude** [comment]
Nevermind. Just found https://getanalytics.io/resources/faq/#how-is-this-different-than-segment.

**Comment by DavidWells** [comment]
Yeah you can use this instead of `analytics.js` from segment.

It depends on where you want your data to flow through.

One major reason this library exists is because `analytics.js` from segment is a very large dep and wasn't pluggable enough for some use cases I was facing.

But yeah you can use them together just fine 😃
