### ISSUE TITLE
Universal Analytics versus Google Analytics 4 ??

### ISSUE THREAD

**Issue by binarykitchen** [DavidWells/analytics#173]
I think this should be documented that the `analytics-plugin-ga` plugin won't work if your Google Analytics account has been set up for Google Analytics 4. And thus `google-tag-manager` should be picked instead.

Because `analytics-plugin-ga` is for the Universal one only.

Took me a while to figure out why not events are tracked when I was on Google Analytics 4 with the wrong plugin.

**Comment by doublejosh** [comment]
Similarly `@analytics/google-analytics` event tracking doesn't work for GA4 running through GTM. I'm kinda shocked, since I'd assume this is a core normal setup for this suite of packages. Still trying to prove it's my fault :)

Click events do not fire. I believe the problem is this package uses the old syntax...
`ga('send', 'MyEvent', 'Click')`
-vs-
`gtag('event', 'click', {})`.

**UPDATE:** Indeed, if you use GTM to trigger GA then you must create tracking events via `@analytics/google-tag-manager`. This pushes to the dataLayer, which is visible in the Tag Assistant debugger. But you still have to configure GTM to trigger a GA tag event. 😧

**Comment by dobesv** [comment]
It looks like since this issue was created, `@analytics/google-analytics` was changed to send events to GA4 and `@analytics/google-analytics-v3` can be used to send events to the prior version.

**Comment by DavidWells** [comment]
At long last, GA4 is released via version 1+ of the https://www.npmjs.com/package/@analytics/google-analytics package.

You can install and use via this command

```
npm install @analytics/google-analytics@latest
```

**Note this is a breaking change** and you will need to setup a google analytics 4 property & stream and use its measurement ID.

If you want to continue using older google analytics 3, which is honestly a completely different product, you will want to switch to the https://www.npmjs.com/package/@analytics/google-analytics-v3 package.

**Using both GA3 and GA4*

It is possible to use both GA3 and GA4 together like so:

```js
import Analytics from 'analytics'
import googleAnalyticsPlugin from '@analytics/google-analytics'
import googleAnalyticsV3Plugin from '@analytics/google-analytics-v3'

/* Initialize analytics instance */
const analytics = Analytics({
  app: 'my-app',
  plugins: [
    /* Load Google Analytics v4 */
    googleAnalyticsPlugin({
      measurementIds: ['G-abc123'],
    }),
    /* Load Google Analytics v3 */
    googleAnalyticsPlugin({
      trackingId: 'UA-11111111-2',
    }),
  ],
})

analytics.page()
```

Just remember GA3 will be deprecated starting in July of 2023
