### ISSUE TITLE
Track callback fires immediately

### ISSUE THREAD

**Issue by has-n** [DavidWells/analytics#195]
I'm trying to track an electron app closing. When I try this, the application quits before the Track call is complete.

```
analytics.track("LoggedOut",()=>{
		app.relaunch();
		app.quit();
	});
```

When I set a timeout and wait for at least 1.5 seconds, it gets tracked.
```	
analytics.track("LoggedOut");
	setTimeout(() => {
		app.relaunch();
		app.quit();
	}, 1500);
```

It would appear as if the callback gets called immediately and not after the Track call is complete.

**Comment by DavidWells** [comment]
Hello there!

This shouldn't be the case. What plugins are you using with analytics?

**Comment by has-n** [comment]
Hey @DavidWells! I'm using the segment plugin. 

This is the setup:

```
const analyticsLib = require('analytics').default
const segmentPlugin = require('@analytics/segment')

const analytics = analyticsLib({
	app: 'Akkompany desktop app',
    debug:true,
	plugins: [
		segmentPlugin({
			writeKey: 'KEY'
		})
	]
})
```

**Comment by DavidWells** [comment]
It appears this is related to a race condition with how the segment batches its API calls.

You will want to either make the call to segment directly or have the timeout as you mention.

It's possible to alter the plugin to be a blocking call here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L135-L138 but I'm not sure this is desirable as a default because this would block any other analytic plugins until segment one completes...

**Comment by has-n** [comment]
> You will want to either make the call to segment directly

Did you mean using the official Segment SDK? 

> I'm not sure this is desirable as a default

I agree. I might stick with the timeout method for now.

**Comment by DavidWells** [comment]
Yeah you can turn down the flush interval like so:

```js
const analyticsLib = require('analytics').default
const segmentPlugin = require('@analytics/segment')

const analytics = analyticsLib({
  app: 'Akkompany desktop app',
  debug:true,
  plugins: [
		segmentPlugin({
			writeKey: 'KEY', 
			flushInterval: 500 // milliseconds
		})
	]
})
```

https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/node.js#L11

Or the timeout approach
