### ISSUE TITLE
GA event tracking

### ISSUE THREAD

**Issue by maartenbrakkee** [DavidWells/analytics#3]
First of all: nice work!

How can I migrate my Google Analytics event tracking with a category, action and label to analytics? The event tracking implementation from Google:

`ga('send', 'event', [eventCategory], [eventAction], [eventLabel], [eventValue], [fieldsObject]);`

**Comment by DavidWells** [comment]
Hey @maartenbrakkee 

Thanks!

You should be able to do something like this:

```js
/* instance.js */
import Analytics from 'analytics'
import googleAnalytics from 'analytics-plugin-ga'

/* initialize analytics and load plugins */
const analytics = Analytics({
  debug: true,
  plugins: [
    googleAnalytics({
      trackingId: 'yourGAID'
    }),
  ]
})
```

Then use it in your app

```js
import analytics from '/instance'

analytics.track('eventName', {
  label: 'foo', 
  value: 10, 
  category: 'bar'
})
```

This maps down to the GA call here https://github.com/DavidWells/analytics/blob/cfd94ff8bf094a6024e824260238bc03eaf0d70f/packages/analytics-plugin-ga/src/browser.js#L107

**Comment by maartenbrakkee** [comment]
Thank you!

**Comment by slidenerd** [comment]
Would be super awesome if you could update the docs and indicate how it could be used as fallback

Use case
- Currently seems like the server side and client side version will not track everything that a native script can (the one pasted from google s website)
- But at the same time, since people disable analytics on client side more often than not, we definitely need a library of this caliber
- Is it possible to do something like if (google analytics not blocked) use native script on client and forget about server side
- If google analytics is blocked, enable client side to send events to server side and process them just as the examples show
- Could you add some example or info in the documentation for this type of use-case if it isn't too much to ask
