### ISSUE TITLE
Add an example with nextjs 

### ISSUE THREAD

**Issue by stunaz** [DavidWells/analytics#46]

**Comment by DavidWells** [comment]
Hey, @stunaz this is a great idea!

I was about to set this up with next.js v8 a while back but the router was changing somehow for v9.

Do you know of any up to date examples of next.js with routing I can take a look at?

**Comment by stunaz** [comment]
sure they are all here https://github.com/zeit/next.js/tree/canary/examples

**Comment by DavidWells** [comment]
Wow, tons of examples there! Thanks

Do you know which might be the most bare-bones with a couple of pages + routing setup? 😃

**Comment by stunaz** [comment]
using-router...

**Comment by kylemh** [comment]
Assuming you're running it just on the client...

You'd want to initalize exactly as your first usage example on the README in `_app.js` on `componentDidMount`, but obviously `analytics` as a variable wouldn't be in scope for the rest of the repository. You could either bind it to the window in that same place or recreate a shallow layer of your API like you did in the React example so that the module is importable throughout the project.

For implicit page view events, it's as simple as [this](https://github.com/OperationCode/front-end/pull/1096/files#diff-13b175b22785184967bd1c87e42ec293R139).

For what it's worth, I [just ditched ReactGA to go straight to the horses mouth with `gtag`](https://github.com/OperationCode/front-end/pull/1096/files), but I'm open to changing to this library if you open a PR to integrate. Then you could point to us for a working and integrated example.

**Comment by DavidWells** [comment]
Hey @stunaz we found an example in the wider community https://github.com/gragland/divjoy-next-zeit/blob/master/util/analytics.js 

That should get you started 😃

I will likely port the preact example https://analytics-preact-example.netlify.com/ to a next one in the next week or so

**Comment by thilak-rao** [comment]
The example above is 404 because the repo got renamed. 

New URL: https://github.com/gragland/divjoy-next-vercel/blob/master/src/util/analytics.js

**Comment by thilak-rao** [comment]
Not sure if this is the best approach, but this is how I use this package on my next.js blog - https://gitlab.com/trao/trao.dev/-/blob/master/hooks/useAnalytics.tsx

EDIT: I just learned about [`useAnalytics` hook](https://github.com/DavidWells/analytics/tree/master/packages/use-analytics). I'm going to refactor my code to use this.

**Comment by DavidWells** [comment]
Nice @xthilakx! 

Love seeing custom plugins like this https://gitlab.com/trao/trao.dev/-/blob/master/utils/analytics.ts#L69-79 😃

The API side looks nice as well https://gitlab.com/trao/trao.dev/-/blob/master/pages/api/t.ts

**Comment by thilak-rao** [comment]
@DavidWells Thanks for all the great work with this package! If there is anything I could do to help out, please let me know!  

Happy to open a pull request which adds a next.js example on both this repo as well as next repo.

**Comment by DavidWells** [comment]
@xthilakx a next.js example would be awesome to see in here 😃

**Comment by DavidWells** [comment]
Another next.js example can be found here:

- Initialization https://github.com/DavidWells/awesome-stoicism/blob/05e065fa89d138ebdc875da3639529ebabaeec13/site/utils/analytics/index.js
- Usage: https://github.com/DavidWells/awesome-stoicism/blob/master/site/pages/_app.js#L12

Going to close this issue for now. Please feel free to add more examples if you find them 😃

**Comment by joshsny** [comment]
@DavidWells Thanks for these examples. The last one helped me a lot and I managed to adapt it to work nicely with NextAuth to track logged in users.

Are there any examples of using analytics in API Routes for NextJS, struggling to get it setup, seems like events don't get sent in time before the serverless function is shutdown...

**Comment by kylemh** [comment]
Hey David. I feel like it may be time to open this issue again because of the [`<Script>` component](https://nextjs.org/docs/basic-features/script).

You can see in their [Google example](https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_app.js), Vercel is emphasizing a performant integration with gtag.

How can we incorporate that into setup?
